In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
columns = [
    "Status", "Duration", "Credit_History", "Purpose",
    "Credit_Amount", "Savings", "Employment",
    "Installment_Rate", "Personal_Status_Sex",
    "Other_Debtors", "Residence_Since",
    "Property", "Age", "Other_Installment_Plans",
    "Housing", "Existing_Credits",
    "Job", "Dependents",
    "Telephone", "Foreign_Worker",
    "Risk"
]

df = pd.read_csv('/Users/ayushsingh/Deep Learning/Financial Risk Management Project/Datasets/statlog+german+credit+data/german.data', sep=" ", header=None)
df.columns = columns

In [9]:
df.head()

,Status,Duration,Credit_History,Purpose,Credit_Amount,Savings,Employment,Installment_Rate,Personal_Status_Sex,Other_Debtors,...,Property,Age,Other_Installment_Plans,Housing,Existing_Credits,Job,Dependents,Telephone,Foreign_Worker,Risk
0,A11,6,A34,A43,1169,A65,A75,4,A93,A101,...,A121,67,A143,A152,2,A173,1,A192,A201,1
1,A12,48,A32,A43,5951,A61,A73,2,A92,A101,...,A121,22,A143,A152,1,A173,1,A191,A201,2
2,A14,12,A34,A46,2096,A61,A74,2,A93,A101,...,A121,49,A143,A152,1,A172,2,A191,A201,1
3,A11,42,A32,A42,7882,A61,A74,2,A93,A103,...,A122,45,A143,A153,1,A173,2,A191,A201,1
4,A11,24,A33,A40,4870,A61,A73,3,A93,A101,...,A124,53,A143,A153,2,A173,2,A191,A201,2

In [10]:
df.columns

Index(['Status', 'Duration', 'Credit_History', 'Purpose', 'Credit_Amount',
       'Savings', 'Employment', 'Installment_Rate', 'Personal_Status_Sex',
       'Other_Debtors', 'Residence_Since', 'Property', 'Age',
       'Other_Installment_Plans', 'Housing', 'Existing_Credits', 'Job',
       'Dependents', 'Telephone', 'Foreign_Worker', 'Risk'],
      dtype='str')

In [12]:
#Risk Categorization

Risk = 1 → Good <br>
Risk = 2 → Bad

In [11]:
df["Risk"] = df["Risk"].map({1:0, 2:1})

Now:<br>
0 = Good<br>
1 = Bad

In [13]:
df.isnull().sum()

Status                     0
Duration                   0
Credit_History             0
Purpose                    0
Credit_Amount              0
Savings                    0
Employment                 0
Installment_Rate           0
Personal_Status_Sex        0
Other_Debtors              0
Residence_Since            0
Property                   0
Age                        0
Other_Installment_Plans    0
Housing                    0
Existing_Credits           0
Job                        0
Dependents                 0
Telephone                  0
Foreign_Worker             0
Risk                       0
dtype: int64

In [16]:
df.describe()

,Duration,Credit_Amount,Installment_Rate,Residence_Since,Age,Existing_Credits,Dependents,Risk
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,20.903000,3271.258000,2.973000,2.845000,35.546000,1.407000,1.155000,0.300000
std,12.058814,2822.736876,1.118715,1.103718,11.375469,0.577654,0.362086,0.458487
min,4.000000,250.000000,1.000000,1.000000,19.000000,1.000000,1.000000,0.000000
25%,12.000000,1365.500000,2.000000,2.000000,27.000000,1.000000,1.000000,0.000000
50%,18.000000,2319.500000,3.000000,3.000000,33.000000,1.000000,1.000000,0.000000
75%,24.000000,3972.250000,4.000000,4.000000,42.000000,2.000000,1.000000,1.000000
max,72.000000,18424.000000,4.000000,4.000000,75.000000,4.000000,2.000000,1.000000

In [21]:
def detect_outliers(column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[(df[column] < lower) | (df[column] > upper)]
    
    print(f"{column} Outliers Count:", len(outliers))

detect_outliers("Credit_Amount")
detect_outliers("Duration")
detect_outliers("Age")

Credit_Amount Outliers Count: 72
Duration Outliers Count: 70
Age Outliers Count: 23